const ActionType = {
    LOADING: 'LOADING',
    FETCH_LOCATION: 'FETCH_LOCATION',
    FETCH_OUTLET: 'FETCH_OUTLET',
    SET_LOCATION: 'SET_LOCATION',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    SET_MAP_CENTER: 'SET_MAP_CENTER',
}

export default ActionType;




